#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/../../autoload.php';

use Chop\Kernel;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;

(new SingleCommandApplication())
    ->addArgument('fcgi', InputArgument::OPTIONAL, 'Path to a socket file or network address.')
    ->addOption('quiet', 'q')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $kernel = new Kernel($input->getArgument('fcgi'));

        $status = $kernel->reset();

        if (!$status) {
            if (!$input->getOption('quiet')) {
                $output->writeln('<error>OPcache disabled</error>');
            }

            return Command::FAILURE;
        }

        if (!$input->getOption('quiet')) {
            $output->writeln(sprintf('<info>OPcache cleared (%s)</info>',
                $kernel->host
            ));
        }

        return Command::SUCCESS;
    })
    ->run();